version: '3'
services:
  l9vitedev-nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./docker/php
    user: "1000:1000"
    ports:
      - 5173:5173
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command:
      mysqld --default-authentication-plugin=mysql_native_password
    user: "1000:1000"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf


  l9vitedev-redis:
    image: redis:alpine
    ports:
      - 16380:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80